name: Semantic Release

on:
  push:
    branches:
      - dev*
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release # Avoids two 'release' pipelines running at the same time.

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Python Semantic Release needs access to the full history.

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
